### ISSUE TITLE
Unknown calculated type

### ISSUE THREAD

**Issue by wheredoesyourmindgo** [ox-it/python-sharepoint#10]
/usr/local/lib/python2.7/dist-packages/sharepoint/lists/types.py:381: UserWarning: Unknown calculated type 'string'
  warnings.warn("Unknown calculated type '%s'" % type_name)

**Comment by bruienne** [comment]
Although the issue was close, I wanted to note that I ran into this issue when new `CalculatedField` fields were added to an SP list I need to work with. I'm unsure after reading MS's docs on `CalculatedField` why only floats are considered valid for the field type as seen [here](
https://github.com/ox-it/python-sharepoint/blob/ab2e1c1b26c7b1d0845e0488bac59f5c6800329d/sharepoint/lists/types.py#L389):

```types = {'float': float}```

but after changing this to: 

```types = {'float': float, 'string': str}```

the warning went away. If needed I can submit a PR for the change.
